version: "3"

services:

  places-engine:
    build: ./places_app
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: places_app.py
    ports: [ '5000:5000' ]
    volumes: [ './places_app:/places_app' ]

  recommendations-engine:
    build: ./recommendations_app
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: recommendations_app.py
    ports: [ '5001:5000' ]
    volumes: [ './recommendations_app:/recommendations_app' ]
